### ISSUE TITLE
Integration with React Router 4's BrowserRouter

### ISSUE THREAD

**Issue by darrentorpey** [pshrmn/qhistory#2]
I had some trouble getting `qhistory` working with React Router 4's `BrowserRouter` component but eventually found a nice solution. The example currently in the README only works for RR4's base Router class which is only meant for deep integration. The RR4 guys fully intend for `qhistory`-like extension so it'd be good to show clearly how to do that.

Here's my pull request to update the README:
https://github.com/pshrmn/qhistory/pull/1

**Comment by pshrmn** [comment]
Let's just keep the discussion in #1.
